# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  html-docs:
    docker:
      - image: circleci/python:3.6
    steps:
      - add_ssh_keys:
        fingerprints:
          - "04:5c:de:15:be:f3:f0:db:88:c4:ce:e7:35:2b:b9:13"
      - checkout
      - run:
        name: "Install Python dependencies"
        command: |
            python3 -m venv venv
            . venv/bin/activate

